In [1]:
#importing the required libraries
import pandas as pd
import numpy as np
import os.path

In [2]:
def Extract_data_from_portfolio(portfolio_name):
    pre="./testing_portfolios/"
    df_temp=pd.read_csv(pre+portfolio_name)
    processed_data=dict()
    kin,_=portfolio_name.split(".")
    processed_data['ID']= kin[5:]
    processed_data['Vehicle_Territory_Avg']=np.mean(df_temp['Vehicle_Territory'])
    processed_data['Vehicle_Territory_std']=np.std(df_temp['Vehicle_Territory'])
    processed_data['Vehicle_Make_Year_Avg']=np.mean(df_temp['Vehicle_Make_Year'])
    processed_data['Vehicle_Make_Year_std']=np.std(df_temp['Vehicle_Make_Year'])
    df_temp['Vehicle_Performance'] = df_temp['Vehicle_Performance'].map({'Standard': 0, 'Intermediate': 1,'High':2, 'Sports':3, 'Sports Premium':4 })
    processed_data['Vehicle_Performance_Avg']=np.mean(df_temp['Vehicle_Performance'])
    processed_data['Vehicle_Performance_Std']=np.std(df_temp['Vehicle_Performance'])
    processed_data['Vehicle_New_Cost_Amount_Avg']=np.mean(df_temp['Vehicle_New_Cost_Amount'])
    processed_data['Vehicle_New_Cost_Amount_Std']=np.std(df_temp['Vehicle_New_Cost_Amount'])
    processed_data['Vehicle_Number_Of_Drivers_Assigned_Avg']=np.mean(df_temp['Vehicle_Number_Of_Drivers_Assigned'])
    processed_data['Vehicle_Number_Of_Drivers_Assigned_Std']=np.std(df_temp['Vehicle_Number_Of_Drivers_Assigned'])
    df_temp['Vehicle_Usage'] = df_temp['Vehicle_Usage'].map({'Farm    ': 0, 'Pleasure': 1,'Work    ':2, 'Business':3 })
    processed_data['Vehicle_Usage_Avg']=np.mean(df_temp['Vehicle_Usage'])
    processed_data['Vehicle_Usage_Std']=np.std(df_temp['Vehicle_Usage'])
    processed_data['Vehicle_Miles_To_Work_Avg']=np.mean(df_temp['Vehicle_Miles_To_Work'])
    processed_data['Vehicle_Miles_To_Work_Std']=np.std(df_temp['Vehicle_Miles_To_Work'])
    df_temp['Vehicle_Annual_Miles'] = df_temp['Vehicle_Annual_Miles'].replace("Unknown", np.nan)
    df_temp['Vehicle_Annual_Miles'] = pd.to_numeric(df_temp['Vehicle_Annual_Miles'], errors='coerce').astype('Int64')
    processed_data['Vehicle_Annual_Miles_Avg']=np.mean(df_temp['Vehicle_Annual_Miles'])
    processed_data['Vehicle_Annual_Miles_Std']=np.std(df_temp['Vehicle_Annual_Miles'])
    df_temp['Vehicle_Anti_Theft_Device'] = df_temp['Vehicle_Anti_Theft_Device'].map({'Unknown': 0, 'Not Applicable': 1, 'Alarm Only':2, 'Active Disabling':3, 'Passive Disabling-Vehicle Recovery':4 })
    processed_data['Vehicle_Anti_Theft_Device_0']=((df_temp[df_temp['Vehicle_Anti_Theft_Device']==0].shape[0]) / df_temp.shape[0])
    processed_data['Vehicle_Anti_Theft_Device_1']=((df_temp[df_temp['Vehicle_Anti_Theft_Device']==1].shape[0]) / df_temp.shape[0])
    processed_data['Vehicle_Anti_Theft_Device_2']=((df_temp[df_temp['Vehicle_Anti_Theft_Device']==2].shape[0]) / df_temp.shape[0])
    processed_data['Vehicle_Anti_Theft_Device_3']=((df_temp[df_temp['Vehicle_Anti_Theft_Device']==3].shape[0]) / df_temp.shape[0])
    processed_data['Vehicle_Age_In_Years_Avg']=np.mean(df_temp['Vehicle_Age_In_Years'])
    processed_data['Vehicle_Age_In_Years_Std']=np.std(df_temp['Vehicle_Age_In_Years'])
    processed_data['Vehicle_Physical_Damage_Limit_Avg']=np.mean(df_temp['Vehicle_Physical_Damage_Limit'])
    processed_data['Vehicle_Physical_Damage_Limit_Std']=np.std(df_temp['Vehicle_Physical_Damage_Limit'])
    processed_data['Vehicle_Collision_Coverage_Deductible_Avg']=np.mean(df_temp['Vehicle_Collision_Coverage_Deductible'])
    processed_data['Vehicle_Collision_Coverage_Deductible_Std']=np.std(df_temp['Vehicle_Collision_Coverage_Deductible'])
    processed_data['Driver_Male_Female_Ratio']=(df_temp['Driver_Total_Male'].sum() / df_temp['Driver_Total_Female'].sum())
    processed_data['Driver_Single_Married_Ratio']=(df_temp['Driver_Total_Single'].sum() / df_temp['Driver_Total_Married'].sum())
    processed_data['Driver_Minimum_Age_Avg']=np.mean(df_temp['Driver_Minimum_Age'])
    processed_data['Driver_Minimum_Age_Std']=np.std(df_temp['Driver_Minimum_Age'])
    processed_data['Driver_Maximum_Age_Avg']=np.mean(df_temp['Driver_Maximum_Age'])
    processed_data['Driver_Maximum_Age_Std']=np.std(df_temp['Driver_Maximum_Age'])
    processed_data['Vehicle_Driver_Points_Avg']=np.mean(df_temp['Vehicle_Driver_Points'])
    processed_data['Vehicle_Driver_Points_Std']=np.std(df_temp['Vehicle_Driver_Points'])
    processed_data['Driver_Total_Senior_Teenager_Ratio'] = (df_temp['Driver_Total_Senior_Ages_65_69'].sum() / df_temp['Driver_Total_Teenager_Age_15_19'].sum())
    processed_data['Driver_Total_Upper_Senior_Middle_Adult_Ratio'] = (df_temp['Driver_Total_Upper_Senior_Ages_70_plus'].sum() / df_temp['Driver_Total_Middle_Adult_Ages_40_49'].sum())
    processed_data['Vehicle_Days_Per_Week_Driven_Avg'] = np.mean(df_temp['Vehicle_Days_Per_Week_Driven'])
    processed_data['Vehicle_Days_Per_Week_Driven_std'] = np.std(df_temp['Vehicle_Days_Per_Week_Driven'])
    processed_data['Vehicle_Physical_Damage_Med_pay_Ratio'] = (df_temp['Vehicle_Physical_Damage_Limit'].sum() / df_temp['Vehicle_Med_Pay_Limit'].sum())
    processed_data['Vehicle_Symbol_Avg'] = np.mean(df_temp['Vehicle_Symbol'])
    processed_data['Vehicle_Symbol_std'] = np.std(df_temp['Vehicle_Symbol'])
    processed_data['Annual_Premium_Avg'] = np.mean(df_temp['Annual_Premium'])
    processed_data['Annual_Premium_std']= np.std(df_temp['Annual_Premium'])
    return processed_data

In [3]:
portfolio_list=list()
for each_portfolio in os.listdir("testing_portfolios"):
    portfolio_list.append(Extract_data_from_portfolio(each_portfolio))

In [4]:
df22 = pd.DataFrame(portfolio_list)
df22 = df22.set_index('ID')
df22.head(5)

,Vehicle_Territory_Avg,Vehicle_Territory_std,Vehicle_Make_Year_Avg,Vehicle_Make_Year_std,Vehicle_Performance_Avg,Vehicle_Performance_Std,Vehicle_New_Cost_Amount_Avg,Vehicle_New_Cost_Amount_Std,Vehicle_Number_Of_Drivers_Assigned_Avg,Vehicle_Number_Of_Drivers_Assigned_Std,...,Vehicle_Driver_Points_Std,Driver_Total_Senior_Teenager_Ratio,Driver_Total_Upper_Senior_Middle_Adult_Ratio,Vehicle_Days_Per_Week_Driven_Avg,Vehicle_Days_Per_Week_Driven_std,Vehicle_Physical_Damage_Med_pay_Ratio,Vehicle_Symbol_Avg,Vehicle_Symbol_std,Annual_Premium_Avg,Annual_Premium_std
ID,,,,,,,,,,,,,,,,,,,,,
portfolio_1,30.896000,4.211316,1996.733000,7.257252,0.071000,0.387245,332.022000,2723.006130,26.897000,43.183659,...,0.357631,1.525000,0.310219,5.000000,0.000000,19.119844,11.129000,3.986020,331.804800,204.070489
portfolio_10,31.087174,4.140980,1997.119238,7.145974,0.080160,0.438145,412.844689,4190.683092,27.929860,43.721645,...,0.352131,1.627907,0.427386,5.001002,0.031639,18.754129,11.294589,3.970506,344.051483,200.954713
portfolio_11,31.195000,4.040170,1996.252000,7.815145,0.084000,0.420647,252.009000,3237.204420,31.610000,45.381890,...,0.405122,1.536585,0.352518,5.000000,0.000000,18.732445,11.015000,4.061868,324.789900,189.020452
portfolio_111,30.973000,4.144426,1997.158000,7.052024,0.077000,0.408743,265.029000,2488.324885,27.096000,43.286219,...,0.409721,2.193548,0.463830,5.000000,0.000000,17.634814,11.184000,4.009507,337.672390,215.676612
portfolio_112,31.053053,4.162393,1996.859860,7.203629,0.071071,0.360672,230.246246,2123.334456,28.888889,44.187183,...,0.374645,1.805556,0.338290,4.994995,0.158114,17.376371,11.245245,4.081614,344.488939,213.186914

In [5]:
df22.describe()

,Vehicle_Territory_Avg,Vehicle_Territory_std,Vehicle_Make_Year_Avg,Vehicle_Make_Year_std,Vehicle_Performance_Avg,Vehicle_Performance_Std,Vehicle_New_Cost_Amount_Avg,Vehicle_New_Cost_Amount_Std,Vehicle_Number_Of_Drivers_Assigned_Avg,Vehicle_Number_Of_Drivers_Assigned_Std,...,Vehicle_Driver_Points_Std,Driver_Total_Senior_Teenager_Ratio,Driver_Total_Upper_Senior_Middle_Adult_Ratio,Vehicle_Days_Per_Week_Driven_Avg,Vehicle_Days_Per_Week_Driven_std,Vehicle_Physical_Damage_Med_pay_Ratio,Vehicle_Symbol_Avg,Vehicle_Symbol_std,Annual_Premium_Avg,Annual_Premium_std
count,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,...,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000
mean,31.053201,4.168199,1996.820492,7.353435,0.076775,0.400974,281.592144,2744.645037,28.375645,43.926961,...,0.381878,1.503722,0.356202,4.999250,0.047880,17.297459,11.210831,4.003268,336.949733,207.489713
std,0.102547,0.144791,0.221042,0.212817,0.009002,0.033084,62.953479,525.569498,0.984063,0.481913,...,0.018130,0.249231,0.031587,0.001555,0.052816,0.935510,0.099742,0.065774,7.015188,9.414972
min,30.685686,3.567348,1996.092092,6.650599,0.048048,0.278875,89.099099,1272.670409,25.166166,42.201794,...,0.330126,0.982456,0.249169,4.993988,0.000000,14.037846,10.858859,3.792066,317.062660,178.731338
25%,30.997331,4.082376,1996.692323,7.219664,0.071071,0.379962,246.153326,2390.140887,27.789500,43.645275,...,0.370065,1.341333,0.338290,4.998610,0.000000,16.768101,11.157355,3.963536,332.596665,202.437933
50%,31.058050,4.164987,1996.805684,7.335757,0.076690,0.402137,278.210092,2695.514766,28.393018,43.951102,...,0.381800,1.484615,0.354019,5.000000,0.030027,17.242820,11.210616,4.000021,336.512540,207.168209
75%,31.113193,4.242980,1996.937933,7.465099,0.082226,0.421899,317.482847,3042.698443,28.947527,44.217483,...,0.394244,1.630239,0.372647,5.000000,0.091440,17.783148,11.269686,4.043199,340.174108,213.182529
max,31.477477,4.644818,1997.529058,8.008821,0.106000,0.516492,517.443443,5267.585332,32.210210,45.640650,...,0.443730,2.571429,0.463830,5.004004,0.190898,21.199193,11.580581,4.283916,359.034134,240.516714

In [6]:
df22.shape

(330, 43)

In [7]:
df22.info()

<class 'pandas.core.frame.DataFrame'>
Index: 330 entries, portfolio_1 to portfolio_9
Data columns (total 43 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Vehicle_Territory_Avg                         330 non-null    float64
 1   Vehicle_Territory_std                         330 non-null    float64
 2   Vehicle_Make_Year_Avg                         330 non-null    float64
 3   Vehicle_Make_Year_std                         330 non-null    float64
 4   Vehicle_Performance_Avg                       330 non-null    float64
 5   Vehicle_Performance_Std                       330 non-null    float64
 6   Vehicle_New_Cost_Amount_Avg                   330 non-null    float64
 7   Vehicle_New_Cost_Amount_Std                   330 non-null    float64
 8   Vehicle_Number_Of_Drivers_Assigned_Avg        330 non-null    float64
 9   Vehicle_Number_Of_Drivers_Assigned_Std        330 non-null    float64
 10  Vehicle_Usage_Avg                             330 non-null    float64
 11  Vehicle_Usage_Std                             330 non-null    float64
 12  Vehicle_Miles_To_Work_Avg                     330 non-null    float64
 13  Vehicle_Miles_To_Work_Std                     330 non-null    float64
 14  Vehicle_Annual_Miles_Avg                      160 non-null    object
 15  Vehicle_Annual_Miles_Std                      160 non-null    object
 16  Vehicle_Anti_Theft_Device_0                   330 non-null    float64
 17  Vehicle_Anti_Theft_Device_1                   330 non-null    float64
 18  Vehicle_Anti_Theft_Device_2                   330 non-null    float64
 19  Vehicle_Anti_Theft_Device_3                   330 non-null    float64
 20  Vehicle_Age_In_Years_Avg                      330 non-null    float64
 21  Vehicle_Age_In_Years_Std                      330 non-null    float64
 22  Vehicle_Physical_Damage_Limit_Avg             330 non-null    float64
 23  Vehicle_Physical_Damage_Limit_Std             330 non-null    float64
 24  Vehicle_Collision_Coverage_Deductible_Avg     330 non-null    float64
 25  Vehicle_Collision_Coverage_Deductible_Std     330 non-null    float64
 26  Driver_Male_Female_Ratio                      330 non-null    float64
 27  Driver_Single_Married_Ratio                   330 non-null    float64
 28  Driver_Minimum_Age_Avg                        330 non-null    float64
 29  Driver_Minimum_Age_Std                        330 non-null    float64
 30  Driver_Maximum_Age_Avg                        330 non-null    float64
 31  Driver_Maximum_Age_Std                        330 non-null    float64
 32  Vehicle_Driver_Points_Avg                     330 non-null    float64
 33  Vehicle_Driver_Points_Std                     330 non-null    float64
 34  Driver_Total_Senior_Teenager_Ratio            330 non-null    float64
 35  Driver_Total_Upper_Senior_Middle_Adult_Ratio  330 non-null    float64
 36  Vehicle_Days_Per_Week_Driven_Avg              330 non-null    float64
 37  Vehicle_Days_Per_Week_Driven_std              330 non-null    float64
 38  Vehicle_Physical_Damage_Med_pay_Ratio         330 non-null    float64
 39  Vehicle_Symbol_Avg                            330 non-null    float64
 40  Vehicle_Symbol_std                            330 non-null    float64
 41  Annual_Premium_Avg                            330 non-null    float64
 42  Annual_Premium_std                            330 non-null    float64
dtypes: float64(41), object(2)
memory usage: 113.4+ KB

In [16]:
df22.to_csv("Final_Testing_data_set.csv")